package com.depromeet.knockknock.util

object KnockKnockIntent {
    const val EXTRA_PUSH_MESSAGE = "PUSH_MESSAGE"
    const val REQUEST_KEY_SUCCESS_SIGNUP = "RESULT_KEY_SUCCESS_SIGNUP"

    const val RESULT_KEY_UPDATE_PROFILE = "RESULT_KEY_UPDATE_PROFILE"
    const val RESULT_KEY_SUCCESS_SIGNUP = "RESULT_KEY_SUCCESS_SIGNUP"
    const val RESULT_KEY_POST_NOTIFICATION_PERMISSION_GRANTED = "RESULT_KEY_POST_NOTIFICATION_PERMISSION_GRANTED"
}